### ISSUE TITLE
ユーザ登録に失敗したように見える

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#176]
ユーザ登録後に以下のエラーが出てました。ユーザの登録自体は成功してます。

![image](https://cloud.githubusercontent.com/assets/2342648/14591221/49e9e08e-0548-11e6-8546-f3a69bd54355.png)

```
Apr 18 09:28:15 meyasubaco app/web.1:  /app/app/signup.js:11 
Apr 18 09:28:15 meyasubaco app/web.1:      if (res.ok) { 
Apr 18 09:28:15 meyasubaco app/web.1:             ^ 
Apr 18 09:28:15 meyasubaco app/web.1:  TypeError: Cannot read property 'ok' of undefined 
Apr 18 09:28:15 meyasubaco app/web.1:      at /app/app/signup.js:9:12 
Apr 18 09:28:15 meyasubaco app/web.1:      at Request.callback (/app/node_modules/superagent/lib/node/index.js:815:12) 
Apr 18 09:28:15 meyasubaco app/web.1:      at /app/node_modules/superagent/lib/node/index.js:1011:43 
Apr 18 09:28:15 meyasubaco app/web.1:      at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/parsers/json.js:14:7) 
Apr 18 09:28:15 meyasubaco app/web.1:      at IncomingMessage.emit (events.js:129:20) 
Apr 18 09:28:15 meyasubaco app/web.1:      at _stream_readable.js:908:16 
Apr 18 09:28:15 meyasubaco app/web.1:      at process._tickDomainCallback (node.js:381:11) 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! Linux 3.13.0-79-generic 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start" 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! node v0.12.0 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! npm  v2.5.1 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! code ELIFECYCLE 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! meyasubaco@0.0.0 start: `babel-node app/server` 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! Exit status 1 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR!  
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! Failed at the meyasubaco@0.0.0 start script 'babel-node app/server'. 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! This is most likely a problem with the meyasubaco package, 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! not with npm itself. 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! Tell the author that this fails on your system: 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR!     babel-node app/server 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! You can get their info via: 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR!     npm owner ls meyasubaco 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! There is likely additional logging output above. 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR! Please include the following file with any support request: 
Apr 18 09:28:15 meyasubaco app/web.1:  npm ERR!     /app/npm-debug.log 
Apr 18 09:28:15 meyasubaco heroku/router:  at=error code=H13 desc="Connection closed without response" method=POST path="/signup" host=meyasuba.co request_id=ae2b5ccc-9a48-4288-aa0f-4fec7af18e56 fwd="211.14.8.249,108.162.226.39" dyno=web.1 connect=1ms service=2521ms status=503 bytes=0 
```

**Comment by shibe97** [comment]
@shoma2da 
ちょっと調べてみたところ、たぶんAPI側で何らかのエラーが出ていると思うんだよなぁ。。
以下のようなものがAPIのレスポンスで返ってきます。詳細はよくわからないけど。。
```
{ [SyntaxError: Unexpected token o] response: undefined }
```
